  
version: '3.4'

services:
  blazorcookieauthapp.App:
    image: fluffybunny/blazorcookieauthapp:latest
    container_name: blazorcookieauthapp
    volumes:
      - ${CERTIFICATE_PATH}:/root/.dotnet/https
    ports:
      - 5000:80
      - 5001:443
    networks:
      - blazorcookieauth-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=${ASPNETCORE_URLS}
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${ASPNETCORE_KESTREL_CERTIFICATE_PASSWORD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=${ASPNETCORE_KESTREL_CERTIFICATE_PATH}
      - ASPNETCORE_HTTPS_PORT=5001
      - externalOIDC__1__authority=${oidc__2__authority}
      - externalOIDC__1__clientId=${oidc__2__clientId}
      - externalOIDC__1__clientSecret=${oidc__2__clientSecret}

   


networks:
  blazorcookieauth-network:
    external: true